# Service with postgres will run during whole pipeline
services:
- name: db
  image: postgres:11
  environment:
  - name: POSTGRES_DB
    value: testdb
  - name: POSTGRES_PASSWORD
    value: dbpass
  - name: POSTGRES_USER
    value: dbuser

steps:
- name: run-tests
  dockerRun:
    image: python:3.7
    script: |
      pip install -r requirements.txt
      pip install -r requirements-test.txt
      flask initdb
      pytest quotes_tests.py
    environment:
    - name: QUOTES_DB_URI
      value: "postgresql+psycopg2://dbuser:dbpass@db:5432/testdb"
    - name: FLASK_APP
      value: quotes.py

- name: build-docker-image
  dockerBuild:
    dockerSecret: dockerhub
    registry: docker.io
    # TODO: change user and image name to repository that you have access to
    user: dandruszak
    imageName: icetek
    tags:
    - "{{ ICE_BUILD_NUMBER }}"
    - latest

